### PR TITLE
Add chain endpoint list

### PR DESCRIPTION
**Pull request by shelvenzhou**

### CODE REVIEW

**Comment by HashWarlock** [comment]
@shelvenzhou update `Summary.md` file to update structure so the site will update with the new page

**Comment by shelvenzhou** [comment]
> @shelvenzhou update `Summary.md` file to update structure so the site will update with the new page

This is fixed, can we merge this?

**Review by HashWarlock — APPROVED** [review]
LGTM

**Review by HashWarlock — APPROVED** [review]
LGTM

**Pull request merged**
